import Head from 'next/head'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import Card from '../components/Card'

const MyChart = dynamic(
  () => import('../components/Chart'),
  { ssr: false }
)

export default function Home() {
  return (
    <div>
      <Head>
        <title>Farm View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='max-w-6xl mx-auto'>
        <nav className='flex items-center justify-between px-4 py-6'>
          {/* Logo */}
          <div>
            <h1>Farm View</h1>
          </div>

          {/* Links */}
          <ul>
            <li>Login</li>
          </ul>
        </nav>
      </header>

      <main className='max-w-2xl mx-auto border border-white grid grid-cols-3 gap-x-4 gap-y-2'>
        <h2 className="text-xl text-slate-700 font-medium mb-2 col-span-3">Bank Balance</h2>

        {/* Bank Balance Chart */}
        <Card className="col-span-2">
          <div className="h-56 w-full">
            <MyChart />
          </div>
        </Card>

        {/* Bank Balance */}
        <Card className="col-span-1 px-4 py-6">
          Hello, world
        </Card>

        {/* Actions Bar */}
        <Card className="px-4 py-6 col-span-3 mt-6">
          <Link href="/map">Go to Map</Link>
        </Card>

        <h2 className="text-xl text-slate-700 font-medium mb-2 col-span-3 mt-6">Market</h2>

        <Card className="px-4 py-6 col-span-3">
          Hello
        </Card>

      </main>
    </div>
  )
}
